### ISSUE TITLE
Add context to your rules!

### ISSUE THREAD

**Issue by OGSteve** [nsacyber/ELITEWOLF#6]
Might I suggest a url reference that shows how these might be found in a malicious context? These were pushed from Proofpoint this week and are extremely noisy with no clear indication of how this activity _might be_ malicious. Anytime you write open source signatures it is a good idea to reference your source for writing said signatures.

For reference, these are the culprits:

1. ET SCADA [nsacyber/ELITEWOLF] Allen-Bradley/Rockwell Automation Advanced Diagnostics Information Disclosure Attempt - TCP Statistics
2. ET SCADA [nsacyber/ELITEWOLF] Allen-Bradley/Rockwell Automation Advanced Diagnostics Information Disclosure Attempt - UDP Statistics
3. ET SCADA [nsacyber/ELITEWOLF] Allen-Bradley/Rockwell Automation System Data Details Information Disclosure Attempt
4. ET SCADA [nsacyber/ELITEWOLF] Allen-Bradley/Rockwell Automation Advanced Diagnostics Information Disclosure Attempt - IP Routing Data
5. ET SCADA [nsacyber/ELITEWOLF] Allen-Bradley/Rockwell Automation Advanced Diagnostics Information Disclosure Attempt - General Memory Statistics
6. ET SCADA [nsacyber/ELITEWOLF] Allen-Bradley/Rockwell Automation Advanced Diagnostics Information Disclosure Attempt - General Heap Memory Statistics
7. ET SCADA [nsacyber/ELITEWOLF] Allen-Bradley/Rockwell Automation Advanced Diagnostics Information Disclosure Attempt - ICMP Statistics
8. ET SCADA [nsacyber/ELITEWOLF] Allen-Bradley/Rockwell Automation Advanced Diagnostics Information Disclosure Attempt - IGMP Statistics
9. ET SCADA [nsacyber/ELITEWOLF] Allen-Bradley/Rockwell Automation Advanced Diagnostics Information Disclosure Attempt - ARP Statistics
10. ET SCADA [nsacyber/ELITEWOLF] Allen-Bradley/Rockwell Automation Advanced Diagnostics Information Disclosure Attempt - Interface Statistics
11. ET SCADA [nsacyber/ELITEWOLF] Allen-Bradley/Rockwell Automation Advanced Diagnostics Information Disclosure Attempt - IP Statistics
12. ET SCADA [nsacyber/ELITEWOLF] Allen-Bradley/Rockwell Automation Possible Unauthorized Access Attempt - Request for radevice.css
13. ET SCADA [nsacyber/ELITEWOLF] Allen-Bradley/Rockwell Automation Information Disclosure Attempt - System List
14. ET SCADA [nsacyber/ELITEWOLF] Allen-Bradley/Rockwell Automation Information Disclosure Attempt - Browse Chasis
15. ET SCADA [nsacyber/ELITEWOLF] Allen-Bradley/Rockwell Automation Information Disclosure Attempt - Chassis Detail Request
16. ET SCADA [nsacyber/ELITEWOLF] Allen-Bradley/Rockwell Automation Information Disclosure Attempt - Crashdump Display
17. ET SCADA [nsacyber/ELITEWOLF] Schweitzer Engineering Laboraties SEL-series Possible Unauthorized Access - Request for home.sel
18. ET SCADA [nsacyber/ELITEWOLF] Schweitzer Engineering Laboraties SEL-series Possible Unauthorized Access Attempt - Request for err401.sel
19. ET SCADA [nsacyber/ELITEWOLF] Schweitzer Engineering Laboratories SEL-series Possible Unauthorized Access - Request for default.sel
20. ET SCADA [nsacyber/ELITEWOLF] Schweitzer Engineering Laboraties SEL-2488 Possible Unauthorized Access Attempt - Request for /scripts/dScripts.sel
21. ET SCADA [nsacyber/ELITEWOLF] Schweitzer Engineering Laboraties SEL-2488 Possible Unauthorized Access Attempt - Request for /css/sel.css
22. ET SCADA [nsacyber/ELITEWOLF] Schweitzer Engineering Laboratories SEL-series Dropbear SSH Banner - Possible SSH Login attempt
23. ET SCADA [nsacyber/ELITEWOLF] Schweitzer Engineering Laboratories SEL-3530-RTAC AcSELerator Firmware Activity
24. ET SCADA [nsacyber/ELITEWOLF] Schweitzer Engineering Laboratories SEL-3620 Default X509 Certificate String
25. ET SCADA [nsacyber/ELITEWOLF] Schweitzer Engineering Laboratories SEL-3620 Default Cert Subject Common Name
26. ET SCADA [nsacyber/ELITEWOLF] Schweitzer Engineering Laboratories SEL-3620 Default Cert Issuer Common Name
27. ET SCADA [nsacyber/ELITEWOLF] Schweitzer Engineering Laboratories SEL-2488 Default Cert Subject Common Name
28. ET SCADA [nsacyber/ELITEWOLF] Schweitzer Engineering Laboratories SEL-2488 Default Cert Issuer Common Name
29. ET SCADA [nsacyber/ELITEWOLF] Schweitzer Engineering Laboratories SEL Telnet Activity
30. ET SCADA [nsacyber/ELITEWOLF] Schweitzer Engineering Laboratories SEL Telnet Elevated Access
31. ET SCADA [nsacyber/ELITEWOLF] Schweitzer Engineering Laboratories SEL 2032 Processor Telnet Banner
32. ET SCADA [nsacyber/ELITEWOLF] Schweitzer Engineering Laboratories SEL Calibration Access Level Login Success
33. ET SCADA [nsacyber/ELITEWOLF] Schweitzer Engineering Laboratories SEL FTP Server Activity - Access Change
34. ET SCADA [nsacyber/ELITEWOLF] Schweitzer Engineering Laboratories SEL FTP Server Activity - Change working directory 2701
35. ET SCADA [nsacyber/ELITEWOLF] Schweitzer Engineering Laboratories SEL FTP Server Activity - Current directory /SEL-2701
36. ET SCADA [nsacyber/ELITEWOLF] Schweitzer Engineering Laboratories SEL FTP Server Activity - DNPMAP.TXT File Download Attempt
37. ET SCADA [nsacyber/ELITEWOLF] Schweitzer Engineering Laboratories SEL FTP Server Activity - STOR SET_DNP1.TXT File Upload Attempt
38. ET SCADA [nsacyber/ELITEWOLF] Schweitzer Engineering Laboratories SEL FTP Server Activity - SET_ File Upload Attempt
39. ET SCADA [nsacyber/ELITEWOLF] Schweitzer Engineering Laboratories SEL FTP Server Activity - User ACC Login Attempt
40. ET SCADA [nsacyber/ELITEWOLF] Schweitzer Engineering Laboratories SEL FTP Server Activity - Default Password otter
41. ET SCADA [nsacyber/ELITEWOLF] Schweitzer Engineering Laboratories SEL FTP Server Activity - DNPMAP.TXT File Upload Attempt
42. ET SCADA [nsacyber/ELITEWOLF] Schweitzer Engineering Laboratories SEL FTP Server Activity - ERR.TXT File Download Attempt
43. ET SCADA [nsacyber/ELITEWOLF] Schweitzer Engineering Laboratories SEL FTP Server Activity - SET_DNP1.TXT File Download Attempt
44. ET SCADA [nsacyber/ELITEWOLF] Schweitzer Engineering Laboratories SEL FTP Server Activity - SET_ File Download Attempt
45. ET SCADA [nsacyber/ELITEWOLF] Schweitzer Engineering Laboratories SEL FTP Server Activity - Default User Account FTPUSER Login Attempt
46. ET SCADA [nsacyber/ELITEWOLF] Schweitzer Engineering Laboratories SEL FTP Server Activity - Default User Account Password TAIL Login Attempt
47. ET SCADA [nsacyber/ELITEWOLF] Schweitzer Engineering Laboratories SEL FTP Server Activity - SEL-751A FTP Banner Observed
48. ET SCADA [nsacyber/ELITEWOLF] Possible Siemens S7-1200 Unauthorized Access Attempt - Request for /Images/CPU1200/
49. ET SCADA [nsacyber/ELITEWOLF] Possible Siemens S7-1200 Unauthorized Access Attempt - Request for /CSS/S7Web.css
50. ET SCADA [nsacyber/ELITEWOLF] Siemens S7-1200 Default X509 Certificate String
51. ET SCADA [nsacyber/ELITEWOLF] Siemens S7-1200 Default Cert Subject Common Name
52. ET SCADA [nsacyber/ELITEWOLF] Siemens S7-1200 Default Cert Issuer Common Name
53. ET SCADA [nsacyber/ELITEWOLF] Siemens S7 Redpoint NSE Request CPU Function Read SZL attempt
54. ET SCADA [nsacyber/ELITEWOLF] Tridium NiagaraAX Default X509 Certificate String
55. ET SCADA [nsacyber/ELITEWOLF] Tridium NiagaraAX Default Cert Subject Common Name
56. ET SCADA [nsacyber/ELITEWOLF] Tridium NiagaraAX Default Cert Issuer Common Name
57. ET SCADA [nsacyber/ELITEWOLF] Tridium NiagaraN4 Default X509 Certificate String
58. ET SCADA [nsacyber/ELITEWOLF] Tridium NiagaraN4 Default Cert Subject Common Name
59. ET SCADA [nsacyber/ELITEWOLF] Tridium NiagaraN4 Default Cert Issuer Common Name
60. ET SCADA [nsacyber/ELITEWOLF] Tridium Niagara4 Default X509 Certificate String
61. ET SCADA [nsacyber/ELITEWOLF] Tridium Niagara4 Default Cert Subject Common Name
62. ET SCADA [nsacyber/ELITEWOLF] Tridium Niagara4 Default Cert Issuer Common Name
63. ET SCADA [nsacyber/ELITEWOLF] Tridium Niagara Default X509 Certificate
64. ET SCADA [nsacyber/ELITEWOLF] Tridium Niagara Default Cert Subject Common Name
65. ET SCADA [nsacyber/ELITEWOLF] Tridium Niagara Default Cert Issuer Common Name

**Comment by da667** [comment]
Hi there, 

My name is Tony, I work on the ProofPoint Emerging Threats team, and I wanted take a stab at answering this question for you.

First and foremost my understanding of the ELITEWOLF ruleset is that it does _not_ exist to detect particularly malicious activity against the ICS controllers covered by the rules, but exists as a sort of 'auditing' ruleset.

What that means is that these rules are meant to detect mostly routine activity or fingerprints that can identify connection attempts to specific controllers -- Telnet Banners, Specific Webpages, SSH versions, Default SSL Certificates, etc. The ruleset also includes a few rules that detects suspicious activity as well -- retrieving or uploading specific files via FTP, using default credentials, or viewing certain webpages that contain specific system data about the controller in question.

Again, by default, these are actions that are not _overtly_ malicious, but depending on the context, could be an indicator of anomalous activity. In my mind, there are two specific use cases for these rules:

 - Using them to establish an audit trail of activity relating to ICS controllers
   - Who is accessing these controllers? 
   - What actions are they taking?
   - When did these actions occur?
   
 - Using the rules to detect said "normal" activity from unusual sources, or to unusual destinations.
   - Let's say you have a lot of these rules triggering. And that its all for seemingly normal traffic. But when you sort the alerts by the IP addresses accessing the controllers, you start seeing IP addresses you don't recognize. Of course you'd want to know about those events, in order to know if anything was tampered with.

Unfortunately, the ET team has to account for wide variations in how IDS rules are deployed. So by default, the rule headers for most of these rules in which the client is attempting to access a controller is usually going to be:

`alert [tcp/http/ssh/etc.] any any -> $HOME_NET any`

Whereas for rules in which the controller is responding to an access request, the rule header is going to look like:

`alert [tcp/tls/etc.] $HOME_NET any -> any any`

This is because we have to account for cases of unauthorized access in which controllers are being access both from within an internal network, as well as from the network perimeter. Now, if the rules in their current state do not serve your purpose, then there are a number of methods available in both Snort and Suricata that can be use to reduce the volume of alerts in order to reduce alert fatigue:

- Disabling the rules altogether
- Disabling the rules, and creating a local rule that excludes a subnet from which the traffic is expected (e.g. creating 'pass' rules)
- Creating a local rule and modifying it with the `threshold` keyword to limit the number of alerts over a given time period
- Setting global threshold config files in either Snort or Suricata and defining either thresholds or supressions in that file. Users can create a suppression to prevent rules from alerting based on source or destination IP address criteria. Its a little bit easier than disabling the current rule and increating a new local rule or pass rule.
- Utilizing BPF, or other low-level capture card logic to prevent Snort or Suricata from seeing the traffic in the first place.

I detailed these options for alert fatigue management on our community website [here](https://community.emergingthreats.net/t/nsacyber-elitewolf-rules-now-in-etopen/1066).  I hope this helps to explain the purpose of these rules as well as addressing options to combat alert fatigue. Happy Hunting, and good luck.

**Comment by OGSteve** [comment]
Well written and informative, I appreciate your response and time. Unfortunately, most teams don't have the time to tune 65 rules without playbooks to create higher confidence/more bespoke detections, especially when monitoring multiple environments. For now at least, we've gone ahead and disabled them.

Again, thanks for the response, it was helpful!
